EE_OBJS_DIR = obj/

EE_BIN = doom.elf

EE_INCS = -I$(PS2SDK)/ports/include/SDL
EE_LDFLAGS = -L$(PS2SDK)/ports/lib -L$(PS2DEV)/gsKit/lib 
EE_LIBS = -lsdlmain -lsdl -lgskit -lcdvd -lmf -lps2ip -lsdl

all: $(EE_BIN)

clean:
	rm -f $(EE_OBJS_DIR) $(EE_BIN)

run:
	ps2client execee host:$(EE_BIN)

reset:
	ps2client reset

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal

